server:
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

jwt:
  secret: ${JWT_SECRET:monsecretjwtformatec2026trèslongetimprévisible}
  expiration: 86400000   # 24h

logging:
  level:
    com.formatec: DEBUG